name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the current branch name
      id: ref
      shell: bash
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -Pversion=${{ steps.ref.outputs.branch }}-${{ github.sha }}
    - name: JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: gunpowder-recipe-${{ steps.ref.outputs.branch }}-${{ github.sha }}.jar
        path: build/libs/gunpowder-recipe-${{ steps.ref.outputs.branch }}-${{ github.sha }}.jar
        if-no-files-found: error
